#ifndef TEXTFORCONTINGENCIES_H
#define TEXTFORCONTINGENCIES_H


#define ACCEPTED_OFFER_BUYER ""
#define CLOSING_BUYER "You will need a valid driver's license and either a cashier's check or a wire transfer of any funds you are bringing to closing. Your lender provides a closing disclosure a week or so prior to closing which will have listed on it the funds you will need to bring to closing in order to close the transaction."
#define CONDITION_REPORT_BUYER "Seller must provide a condition report, if they do not provide one you will have two business days to rescind the offer."
#define EARNEST_MONEY1_BUYER "Check should be made out to "
#define EARNEST_MONEY_SUB1_BUYER "the listing broker's trust account"
#define EARNEST_MONEY2_BUYER " for "
#define EARNEST_MONEY_SUB2_BUYER "the agreed upon amount"
#define EARNEST_MONEY3_BUYER ". Please write "
#define EARNEST_MONEY_SUB3_BUYER  "the property's address"
#define EARNEST_MONEY4_BUYER " on the memo line."
#define INSPECTION_BUYER "We must complete the inspection and any negotiations for repairs by this date."
#define APPRAISAL_BUYER "Your lender will schedule the appraisal.  Lenders want an independent third party to verify the fair market value of the home so they require an appraisal as part of the loan application.  This contingency also protects you in the event the home does not appraise for the offer price."
#define FINANCING_BUYER "To satisfy this contingency, your lender will provide a loan commitment letter to you.  You will need to direct us in writing to deliver the letter to the seller.  Delivery of the loan commitment waives your financing even if there are still lender conditions to be met so review your loan commitment carefully prior to delivering it to the seller."
#define FINAL_WALKTHROUGH_BUYER "This is your last opportunity to look over the property to make sure that it is in the same relative condition as you remember.   The offer states ...Property shall be in broom swept condition and free of all debris and personal property...  See lines 57 - 60."
#define RADON_BUYER "Radon test must be completed and negotiated by this date but we will likely have it done at the same time as the inspection."
#define CONDO_DOCS_BUYER "This is your opportunity to review any Condominium Documents such as the Rules and Regulations or the Minutes and Budget.  If you have questions with regard to anything in these documents, you may want to have an attorney review them for you."
#define WELL_SEPTIC_BUYER "For properties served by a well and septic system, you will need to have a separate inspection of those components by a specialist. Any water testing must be asked for in the Offer."
#define COMFORT_LETTER_BUYER "We must provide the seller a bank letter by this date."
#define ENVIRONMENTAL_TEST_BUYER  "Any environmental testing such as asbestos or mold must be completed by this date and asked for in the offer."
#define ATTORNEY_REVIEW_BUYER "This is your opportunity to have the Offer documents reviewed by an attorney."
#define HOME_OWNER_INSSURENCE_BUYER "You should arrange for home owner's insurance as soon as we are done with the inspection.  You will be required to pay the first year in full.  Please have your insurance agent send a copy of the paid insurance binder to your lender."
#define SEWER_BUYER "We must have the sewer inspected and any repairs negotiated by this date."
#define ZONING_BUYER "Any zoning or land use issues must be resolved by this date."
#define SURVEY_BUYER "The survey must be completed and any lot line issues resolved by this date."
#define RATE_LOCK_BUYER "Financing issues can arise if the closing date is pushed out past this date."

#define ORDER_TITLE_BUYER "tile order buyer"
#define HOA_DOCS_DELIVERY_BUYER "HOA docs delivery bueyr"
#define HOA_DOCS_REVIEW_BUYER "HOA docs review buyer"
#define COVENANTS_RESTRICTIONS_DELIVERY_BUYER "cov and res delivery"
#define COVENANTS_RESTRICTIONS_REVIEW_BUYER "cov and restrictions review buyer"
#define REVIEW_CONDO_DOCS_BUYER " Text for buyer review of condo docs-------"
#define CONDITON_REPORT_REVIEW_BUYER "text for reviewing condition report -----------------"

//-----------------------------------------

#define ACCEPTED_OFFER_SELLER ""
#define CLOSING_SELLER "You will need a valid driver's license and either a cashier's check or a wire transfer of any funds you are bringing to closing. The title company will provide a closing disclosure to you a week or so prior to closing.  The disclosure will list the funds you will need to bring to closing in order to close the transaction."
#define CONDITION_REPORT_SELLER "You must provide a copy of the Real Estate Condition Report to the buyer by this date. If they do not receive one the buyer will have two business days to rescind the offer."
#define EARNEST_MONEY1_SELLER "The buyer must have the earnest money check "
#define EARNEST_MONEY2_SELLER "written for the amount of "
#define EARNEST_MONEY3_SELLER "delivered by this date.  A copy of the receipt will be delivered to all parties.  The funds will be held in "
#define EARNEST_MONEY4_SELLER "trust"
#define EARNEST_MONEY5_SELLER " and put toward the purchase of the home at closing."
#define INSPECTION_SELLER "The buyer must complete the home inspection and any negotiations for repairs by this date."
#define APPRAISAL_SELLER "The buyer’s lender will usually schedule the appraisal.  Lenders want an independent third party to verify the fair market value of the home so they require an appraisal as part of the loan application. You will not need to be present for this."
#define FINANCING_SELLER "Delivery of the loan commitment waives the buyer’s financing even if there are still lender conditions."
#define FINAL_WALKTHROUGH_SELLER "This is the buyer’s last opportunity to look over the property to make sure that it is in the same relative condition as when they last saw it.   The offer states ...Property shall be in broom swept condition and free of all debris and personal property...  See lines 57 - 60."
#define RADON_SELLER "Radon testing and negotiations must be completed by this date. The buyer will likely have it done at the same time as the inspection."
#define CONDO_DOCS_SELLER "You are required provide any condominium documents, such as the Rules and Regulations or the Minutes and Budget, to the buyer by this date.  The buyer will then have five business days after receipt to rescind the offer."
#define WELL_SEPTIC_SELLER "The buyer will need to have a separate inspection of the well and/or septic system by a specialist. Any water testing must be asked for in the offer."
#define COMFORT_LETTER_SELLER "The buyer must provide the requested assurances by this date."
#define ENVIRONMENTAL_TEST_SELLER "Any environmental testing such as asbestos or mold must be completed by this date and asked for in the offer."
#define ATTORNEY_REVIEW_SELLER "This is your opportunity to have the offer and associated documents reviewed by an attorney."
#define HOME_OWNER_INSSURENCE_SELLER "The buyer will need to arrange for home-owner’s insurance in order to close the transaction."
#define SEWER_SELLER "We must have the sewer inspected and any repairs negotiated by this date."
#define ZONING_SELLER "Any zoning or land use issues must be resolved by this date."
#define SURVEY_SELLER "The survey must be completed and any lot line issues resolved by this date."
#define RATE_LOCK_SELLER "Financing issues can arise if the closing date is pushed out past this date."

#define ORDER_TITLE_SELLER "Title text for seller"
#define HOA_DOCS_DELIVERY_SELLER "HOA delievery text for seller"
#define HOA_DOCS_REVIEW_SELLER "HOA review seller "
#define COVENANTS_RESTRICTIONS_DELIVERY_SELLER "Covenants and restrictions delivery"
#define COVENANTS_RESTRICTIONS_REVIEW_SELLER "review covenants restrictions review"
#define REVIEW_CONDO_DOCS_SELLER " Text for SELLER review of condo docs-------"
#define CONDITON_REPORT_REVIEW_SELLER "text for reviewing condition report -----------------"


//-----------------------------------------

#define BLANK "-"
#define EARNEST_MONEY_TITLE "Earnest Money"
#define CONDITION_REPORT_TITLE "Delivery Of Condition Report"
#define FINANCING_TITLE "Financing"
#define APPRAISAL_TITLE "Appraisal"
#define INSPECTION_TITLE "Inspection"
#define RADON_TITLE "Radon Test"
#define WELL_SEPTIC_TITLE "Well & Septic"
#define FINAL_WALKTHROUGH_TITLE "Final Walk-through"
#define HOME_INSURENCE_TITLE "Home-Owner Insurance"
#define CONDO_DOCS_TITLE "Delivery Of Condo Docs"
#define COMFORT_LETTER_TITLE "Comfort Letter"
#define ENVIRONMENTAL_TEST_TITLE "Environmental Test"
#define ATTORNEY_REVIEW_TITLE "Attorney Review"
#define SEWER_TITLE "Sewer"
#define ZONING_TITLE "Zoning"
#define SURVEY_TITLE "Survey"
#define RATE_LOCK_TITLE "Loan Rate Lock Expiration"

#define ORDER_TITLE_TITLE "Order Title"
#define HOA_DOCS_DELIVERY_TITLE "Delivery Of HOA Documents"
#define HOA_DOCS_REVIEW_TITLE "Review HOA Documents"
#define COVENANTS_RESTRICTIONS_DELIVERY_TITLE "Delivery Of Covenants And Restrictions"
#define COVENANTS_RESTRICTIONS_REVIEW_TITLE "Review Covenants and Restrictions"
#define CONDITION_REPORT_REVIEW_TITLE "Review of Condition Report"
#define CONDO_DOCS_REVIEW_TITLE "Review Condo Docs"


#define CUSTOM_TITLE "-Custom-"
#define ACCEPTED_OFFER_TITLE "Offer Accepted"
#define CLOSING_TITLE "Closing"




#endif // TEXTFORCONTINGENCIES_H
